import { AutoAwesomeRounded, CloseRounded, SendRounded } from '@mui/icons-material';
import { Avatar, Box, CircularProgress, Divider, Drawer, IconButton, Paper, Stack, TextField, Typography } from '@mui/material';
import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { askCoach } from '../services/api.js';
import { appendChatMessage } from '../store/assistantSlice.js';

export default function CoachChat({ open, onClose }) {
  const messages = useSelector((state) => state.assistant.messages);
  const dispatch = useDispatch();
  const [question, setQuestion] = useState(''); const [sending, setSending] = useState(false);
  const send = async (event) => { event.preventDefault(); const prompt = question.trim(); if (!prompt || sending) return; dispatch(appendChatMessage({ role: 'user', text: prompt })); setQuestion(''); setSending(true); try { const { data } = await askCoach(prompt); dispatch(appendChatMessage({ role: 'coach', text: data.answer || 'I could not create a response for that just now.' })); } catch { dispatch(appendChatMessage({ role: 'coach', text: 'I’m having trouble reaching the coach service. Please try again in a moment.' })); } finally { setSending(false); } };
  return <Drawer anchor="right" open={open} onClose={onClose} PaperProps={{ sx: { width: { xs: '100%', sm: 420 }, p: 0 } }}><Stack sx={{ height: '100%' }}><Box sx={{ p: 2.5, color: 'common.white', background: 'linear-gradient(135deg, #122C3D, #176B87)' }}><Stack direction="row" justifyContent="space-between" alignItems="center"><Stack direction="row" spacing={1.25} alignItems="center"><Avatar sx={{ bgcolor: 'rgba(255,255,255,.18)' }}><AutoAwesomeRounded /></Avatar><Box><Typography fontWeight={800}>FitFlow AI Coach</Typography><Typography variant="caption" sx={{ opacity: .8 }}>Here to help you move smarter</Typography></Box></Stack><IconButton onClick={onClose} sx={{ color: 'inherit' }}><CloseRounded /></IconButton></Stack></Box><Stack spacing={1.5} sx={{ p: 2, flex: 1, overflowY: 'auto', bgcolor: '#F7FAFC' }}>{messages.map((message, index) => <Box key={`${message.role}-${index}`} sx={{ alignSelf: message.role === 'user' ? 'flex-end' : 'flex-start', maxWidth: '88%' }}><Paper elevation={0} sx={{ p: 1.5, borderRadius: 3, bgcolor: message.role === 'user' ? 'primary.main' : 'common.white', color: message.role === 'user' ? 'primary.contrastText' : 'text.primary', border: message.role === 'coach' ? '1px solid #E4EBF0' : 'none' }}><Typography variant="body2">{message.text}</Typography></Paper></Box>)}{sending && <CircularProgress size={22} sx={{ ml: 1 }} />}</Stack><Divider /><Box component="form" onSubmit={send} sx={{ p: 2, display: 'flex', gap: 1 }}><TextField value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask your coach…" size="small" fullWidth /><IconButton type="submit" disabled={!question.trim() || sending} color="primary"><SendRounded /></IconButton></Box></Stack></Drawer>;
}
